DROP TABLE IF EXISTS base_user_role;
DROP TABLE IF EXISTS base_role_perm;
DROP TABLE IF EXISTS base_user;
DROP TABLE IF EXISTS base_role;
DROP TABLE IF EXISTS base_perm;



CREATE TABLE base_user(
	`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	`username` VARCHAR(255) NOT NULL COMMENT '账号',
	`nickname` VARCHAR(255) NOT NULL COMMENT '账号',
	`password` VARCHAR(500) NOT NULL COMMENT '密码',
	`creater` VARCHAR(255) NOT NULL COMMENT '创建人',
	`create_time` TIMESTAMP NOT NULL COMMENT '创建时间',
	`updater` VARCHAR(255)  COMMENT '更新人',
	`update_time` TIMESTAMP  COMMENT '更新时间',
	salt varchar(64) COMMENT '加密盐值',
	PRIMARY KEY (`id`)
)ENGINE=INNODB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COMMENT '用户表';

CREATE TABLE base_role(
	`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	`name` VARCHAR(255) NOT NULL COMMENT '名称',
	`remark` VARCHAR(1000) COMMENT '描述',
	 PRIMARY KEY (`id`)
)ENGINE=INNODB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COMMENT='角色表';

CREATE TABLE `base_perm` (
   `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
   `name` VARCHAR(255) NOT NULL COMMENT '名称',
   `remark` VARCHAR(1000) NOT NULL COMMENT '描述',
   `parent_id` INT(11) COMMENT '父ID',
   PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COMMENT='资源表';
 
CREATE TABLE base_user_role(
	`user_id` INT(11) NOT NULL COMMENT '用户表ID',
	`role_id` INT(11) NOT NULL COMMENT '角色表ID',
	PRIMARY KEY (`user_id`, `role_id`)
)ENGINE=INNODB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COMMENT='用户角色表';

CREATE TABLE base_role_perm(
	`perm_id` INT(11) NOT NULL COMMENT '资源表ID',
	`role_id` INT(11) NOT NULL COMMENT '角色表ID',
	PRIMARY KEY (`perm_id`, `role_id`)
)ENGINE=INNODB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COMMENT='角色资源表';
